# Generated by Django 5.2.4 on 2025-08-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('p_title', models.CharField(max_length=35)),
                ('p_description', models.TextField()),
                ('p_price', models.FloatField()),
                ('p_posted', models.DateTimeField(auto_now_add=True)),
                ('p_category', models.CharField(choices=[('smartphones', 'Smartphones'), ('laptops', 'Laptops'), ('tablets', 'Tablets'), ('desktop_computers', 'Desktop Computers'), ('gaming_consoles', 'Gaming Consoles'), ('headphones', 'Headphones & Earphones'), ('speakers', 'Speakers'), ('cameras', 'Cameras'), ('smart_watches', 'Smart Watches'), ('televisions', 'Televisions'), ('home_appliances', 'Home Appliances'), ('kitchen_appliances', 'Kitchen Appliances'), ('computer_accessories', 'Computer Accessories'), ('mobile_accessories', 'Mobile Accessories'), ('gaming_accessories', 'Gaming Accessories'), ('audio_equipment', 'Audio Equipment'), ('video_equipment', 'Video Equipment'), ('smart_home', 'Smart Home Devices'), ('wearable_tech', 'Wearable Technology'), ('drones', 'Drones & Quadcopters'), ('mens_clothing', "Men's Clothing"), ('womens_clothing', "Women's Clothing"), ('kids_clothing', "Kids' Clothing"), ('shoes', 'Shoes'), ('bags', 'Bags & Luggage'), ('accessories', 'Fashion Accessories'), ('jewelry', 'Jewelry'), ('watches', 'Watches'), ('sunglasses', 'Sunglasses'), ('hats', 'Hats & Caps'), ('belts', 'Belts'), ('scarves', 'Scarves'), ('underwear', 'Underwear & Lingerie'), ('activewear', 'Activewear'), ('formal_wear', 'Formal Wear'), ('casual_wear', 'Casual Wear'), ('ethnic_wear', 'Ethnic Wear'), ('skincare', 'Skincare'), ('makeup', 'Makeup & Cosmetics'), ('haircare', 'Hair Care'), ('fragrances', 'Fragrances'), ('personal_care', 'Personal Care'), ('health_supplements', 'Health Supplements'), ('fitness_equipment', 'Fitness Equipment'), ('medical_devices', 'Medical Devices'), ('wellness', 'Wellness Products'), ('oral_care', 'Oral Care'), ('mens_grooming', "Men's Grooming"), ('womens_care', "Women's Care"), ('furniture', 'Furniture'), ('home_decor', 'Home Decor'), ('bedding', 'Bedding & Bath'), ('lighting', 'Lighting'), ('storage', 'Storage & Organization'), ('cleaning_supplies', 'Cleaning Supplies'), ('tools', 'Tools & Hardware'), ('garden_supplies', 'Garden & Outdoor'), ('kitchenware', 'Kitchenware'), ('dining', 'Dining & Tableware'), ('bathroom_accessories', 'Bathroom Accessories'), ('wall_art', 'Wall Art & Decor'), ('rugs_carpets', 'Rugs & Carpets'), ('curtains_blinds', 'Curtains & Blinds'), ('plants', 'Plants & Planters'), ('sports_equipment', 'Sports Equipment'), ('outdoor_gear', 'Outdoor Gear'), ('camping', 'Camping & Hiking'), ('cycling', 'Cycling'), ('water_sports', 'Water Sports'), ('winter_sports', 'Winter Sports'), ('team_sports', 'Team Sports'), ('individual_sports', 'Individual Sports'), ('fishing', 'Fishing'), ('hunting', 'Hunting'), ('outdoor_clothing', 'Outdoor Clothing'), ('sports_shoes', 'Sports Shoes'), ('gym_equipment', 'Gym Equipment'), ('books', 'Books'), ('ebooks', 'E-books'), ('audiobooks', 'Audiobooks'), ('magazines', 'Magazines'), ('movies_tv', 'Movies & TV Shows'), ('music', 'Music'), ('video_games', 'Video Games'), ('board_games', 'Board Games'), ('educational_materials', 'Educational Materials'), ('stationery', 'Stationery'), ('groceries', 'Groceries'), ('beverages', 'Beverages'), ('snacks', 'Snacks'), ('organic_food', 'Organic Food'), ('specialty_food', 'Specialty Food'), ('frozen_food', 'Frozen Food'), ('dairy_products', 'Dairy Products'), ('meat_seafood', 'Meat & Seafood'), ('fruits_vegetables', 'Fruits & Vegetables'), ('bakery', 'Bakery Items'), ('condiments', 'Condiments & Sauces'), ('international_food', 'International Food'), ('baby_care', 'Baby Care'), ('baby_clothing', 'Baby Clothing'), ('toys', 'Toys'), ('kids_books', "Kids' Books"), ('baby_gear', 'Baby Gear'), ('feeding', 'Baby Feeding'), ('diapering', 'Diapering'), ('nursery', 'Nursery Furniture'), ('educational_toys', 'Educational Toys'), ('outdoor_toys', 'Outdoor Toys'), ('stuffed_animals', 'Stuffed Animals'), ('car_accessories', 'Car Accessories'), ('car_parts', 'Car Parts'), ('motorcycle_accessories', 'Motorcycle Accessories'), ('tires', 'Tires'), ('car_care', 'Car Care Products'), ('tools_automotive', 'Automotive Tools'), ('electronics_automotive', 'Automotive Electronics'), ('pet_food', 'Pet Food'), ('pet_toys', 'Pet Toys'), ('pet_accessories', 'Pet Accessories'), ('pet_care', 'Pet Care'), ('pet_clothing', 'Pet Clothing'), ('aquarium_supplies', 'Aquarium Supplies'), ('bird_supplies', 'Bird Supplies'), ('reptile_supplies', 'Reptile Supplies'), ('office_supplies', 'Office Supplies'), ('office_furniture', 'Office Furniture'), ('printers_scanners', 'Printers & Scanners'), ('business_equipment', 'Business Equipment'), ('presentation_supplies', 'Presentation Supplies'), ('filing_storage', 'Filing & Storage'), ('art_supplies', 'Art Supplies'), ('craft_materials', 'Craft Materials'), ('sewing_supplies', 'Sewing Supplies'), ('painting_supplies', 'Painting Supplies'), ('drawing_supplies', 'Drawing Supplies'), ('scrapbooking', 'Scrapbooking'), ('knitting_crochet', 'Knitting & Crochet'), ('guitars', 'Guitars'), ('keyboards_pianos', 'Keyboards & Pianos'), ('drums', 'Drums'), ('wind_instruments', 'Wind Instruments'), ('string_instruments', 'String Instruments'), ('music_accessories', 'Music Accessories'), ('recording_equipment', 'Recording Equipment'), ('industrial_supplies', 'Industrial Supplies'), ('scientific_equipment', 'Scientific Equipment'), ('safety_equipment', 'Safety Equipment'), ('laboratory_supplies', 'Laboratory Supplies'), ('measuring_tools', 'Measuring Tools'), ('gift_cards', 'Gift Cards'), ('digital_services', 'Digital Services'), ('subscriptions', 'Subscriptions'), ('experiences', 'Experiences'), ('warranties', 'Warranties & Protection Plans'), ('collectibles', 'Collectibles'), ('antiques', 'Antiques'), ('handmade', 'Handmade Items'), ('vintage', 'Vintage Items'), ('party_supplies', 'Party Supplies'), ('seasonal', 'Seasonal Items'), ('religious_items', 'Religious Items'), ('travel_accessories', 'Travel Accessories'), ('novelty_items', 'Novelty Items'), ('other', 'Other')], max_length=100)),
                ('p_rating', models.FloatField(max_length=5)),
                ('p_updated', models.DateField(auto_now=True)),
                ('p_stock', models.IntegerField()),
                ('p_sold', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_pic', models.ImageField(upload_to='Images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('approved_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('spam', 'Marked as Spam')], default='pending')),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReviews',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('review_rating', models.IntegerField()),
                ('review_desc', models.TextField()),
                ('review_postedat', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('review_image_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_pic', models.ImageField(upload_to='ReviewImages/')),
            ],
        ),
    ]
