# Generated by Django 5.2.4 on 2025-08-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('p_title', models.CharField(max_length=35)),
                ('p_description', models.TextField()),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('p_posted', models.DateTimeField(auto_now_add=True)),
                ('p_rating', models.DecimalField(decimal_places=0, max_digits=1)),
                ('p_updated', models.DateField(auto_now=True)),
                ('p_stock', models.IntegerField()),
                ('p_sold', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_pic', models.ImageField(upload_to='Images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('approved_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('spam', 'Marked as Spam')], default='pending')),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReviews',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('review_rating', models.IntegerField()),
                ('review_desc', models.TextField()),
                ('review_postedat', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('review_image_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_pic', models.ImageField(upload_to='ReviewImages/')),
            ],
        ),
    ]
