# Generated by Django 5.2.4 on 2025-08-01 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_view', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.seller'),
        ),
        migrations.AddField(
            model_name='productanswers',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions_answered', to='users.seller'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product_view.product'),
        ),
        migrations.AddField(
            model_name='productquestion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='product_view.product'),
        ),
        migrations.AddField(
            model_name='productquestion',
            name='status_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions_asked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productanswers',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='product_view.productquestion'),
        ),
        migrations.AddField(
            model_name='productreviews',
            name='review_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='product_view.product'),
        ),
        migrations.AddField(
            model_name='productreviews',
            name='review_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='image_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewImage', to='product_view.productreviews'),
        ),
        migrations.AddConstraint(
            model_name='productreviews',
            constraint=models.UniqueConstraint(fields=('review_user', 'review_product'), name='One review per product Allowed to any User'),
        ),
    ]
