# Generated by Django 5.2.4 on 2025-08-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_seller_seller_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
