# Generated by Django 5.2.4 on 2025-08-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_seller_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='seller_since',
            new_name='since',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='seller_store_name',
            new_name='store_name',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='seller_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='seller_id',
        ),
        migrations.AddField(
            model_name='seller',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
