# Generated by Django 5.2.4 on 2025-08-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_subtotal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('completed', 'Completed'), ('canceled', 'Canceled'), ('pending', 'Pending')], default='pending', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_status', models.CharField(choices=[('staged', 'Staged'), ('packing', 'Packing'), ('dispatched', 'Dispatched'), ('shipped', 'Shipped'), ('arrived', 'Arrived'), ('ofd', 'Out For Delivery'), ('received', 'Received')], default='staged')),
            ],
        ),
    ]
